# Generated by Django 5.1.1 on 2024-10-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(default='The description for the videos'),
            preserve_default=False,
        ),
    ]
